/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio400;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author paula
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Numerador = new javax.swing.JLabel();
        Denominador = new javax.swing.JLabel();
        campoNumerador = new javax.swing.JTextField();
        campoDenominador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoCociente = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Numerador.setText("Numerador");

        Denominador.setText("Denominador");

        campoNumerador.addActionListener(this::campoNumeradorActionPerformed);

        jLabel1.setText("Cociente");

        campoCociente.addActionListener(this::campoCocienteActionPerformed);

        Calcular.setText("Calcular");
        Calcular.addActionListener(this::CalcularActionPerformed);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(this::LimpiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Numerador)
                            .addComponent(Denominador)
                            .addComponent(jLabel1))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNumerador, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(campoDenominador)
                            .addComponent(campoCociente))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numerador)
                    .addComponent(campoNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Denominador)
                    .addComponent(campoDenominador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoCociente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calcular)
                    .addComponent(Limpiar))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNumeradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeradorActionPerformed

    private void campoCocienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCocienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCocienteActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        campoNumerador.setText("");
        campoDenominador.setText("");
        campoCociente.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        try {
            JOptionPane.showMessageDialog(null,"Ingresando al primer try","Atencion",JOptionPane.INFORMATION_MESSAGE);
            double numerador = Double.parseDouble(campoNumerador.getText());
            double denominador = Double.parseDouble(campoDenominador.getText());
                    
            double cociente = numerador/denominador; // Se lanza una excepción
            JOptionPane.showMessageDialog(null,"Después de la división","Atencion",JOptionPane.INFORMATION_MESSAGE);
            
            campoCociente.setText(String.valueOf(cociente));
        } catch (ArithmeticException e) { // Se captura la excepción
            JOptionPane.showMessageDialog(null,"División por cero","Atencion",JOptionPane.INFORMATION_MESSAGE);

        } finally {
            /* La sentencia finally siempre se ejecuta, ocurra o no una
            excepción */
            JOptionPane.showMessageDialog(null,"Ingresando al primer finally","Atencion",JOptionPane.INFORMATION_MESSAGE);
        }
        // Segundo bloque try
        try {
            JOptionPane.showMessageDialog(null,"Ingresando al segundo try","Atencion",JOptionPane.INFORMATION_MESSAGE);
            Object objeto = null;
            objeto.toString(); // Se lanza una excepción
            /* Esta instrucción nunca será ejecutada porque se lanzó una
            excepción */
            JOptionPane.showMessageDialog(null,"Imprimiendo objeto","Atencion",JOptionPane.INFORMATION_MESSAGE);
        } catch (ArithmeticException e) { 
            JOptionPane.showMessageDialog(null,"División por cero","Atencion",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) { // Se captura la excepción
            JOptionPane.showMessageDialog(null,"Ocurrió una excepción","Atencion",JOptionPane.INFORMATION_MESSAGE);
        } finally {
            /* La sentencia finally siempre se ejecuta, ocurra o no una
            excepción */
            JOptionPane.showMessageDialog(null,"Ingresando al segundo finally","Atencion",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JLabel Denominador;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Numerador;
    private javax.swing.JTextField campoCociente;
    private javax.swing.JTextField campoDenominador;
    private javax.swing.JTextField campoNumerador;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
