/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio8_3;

/**
 *
 * @author paula
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setTitle("Figuras");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cilindro = new javax.swing.JButton();
        Esfera = new javax.swing.JButton();
        Pirámide = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cilindro.setText("Cilindro");
        Cilindro.addActionListener(this::CilindroActionPerformed);

        Esfera.setText("Esfera");
        Esfera.addActionListener(this::EsferaActionPerformed);

        Pirámide.setText("Pirámide");
        Pirámide.addActionListener(this::PirámideActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(Cilindro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Esfera)
                .addGap(18, 18, 18)
                .addComponent(Pirámide)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cilindro)
                    .addComponent(Esfera)
                    .addComponent(Pirámide))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CilindroActionPerformed
        // TODO add your handling code here:
        VentanaCilindro cilindro = new VentanaCilindro(); /* Crea la ventana del cilindro */
        cilindro.setVisible(true);
    }//GEN-LAST:event_CilindroActionPerformed

    private void EsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsferaActionPerformed
        // TODO add your handling code here:
        VentanaEsfera esfera = new VentanaEsfera(); /* Crea la ventana de la esfera */
        esfera.setVisible(true); /* Establece que se visualice la ventana 
        de la esfera */
    }//GEN-LAST:event_EsferaActionPerformed

    private void PirámideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PirámideActionPerformed
        // TODO add your handling code here:
        VentanaPirámide pirámide = new VentanaPirámide(); /* Crea la ventana de la pirámide */
        pirámide.setVisible(true);
    }//GEN-LAST:event_PirámideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cilindro;
    private javax.swing.JButton Esfera;
    private javax.swing.JButton Pirámide;
    // End of variables declaration//GEN-END:variables
}
