/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio418;

import javax.swing.JOptionPane;

/**
 *
 * @author paula
 */
public class VentanaEquipo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaEquipo.class.getName());

    /**
     * Creates new form VentanaEquipo
     */
    public VentanaEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreequipo = new javax.swing.JLabel();
        Universidad = new javax.swing.JLabel();
        lenguaje = new javax.swing.JLabel();
        numeroIntegrantes = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();
        campoEquipo = new javax.swing.JTextField();
        campoUniversidad = new javax.swing.JTextField();
        campoLenguaje = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        campoNumeroIntegrantes = new javax.swing.JTextField();
        datos = new javax.swing.JLabel();
        nombreParticipante = new javax.swing.JLabel();
        apellidoParticipante = new javax.swing.JLabel();
        campoNombreParticipante = new javax.swing.JTextField();
        campoApellidoParticipante = new javax.swing.JTextField();
        datosParticipante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreequipo.setText("Nombre del equipo");

        Universidad.setText("Universidad");

        lenguaje.setText("Lenguaje de programación");

        numeroIntegrantes.setText("Número de integrantes");

        Limpiar.setText("Limpiar información equipo");
        Limpiar.addActionListener(this::LimpiarActionPerformed);

        campoEquipo.addActionListener(this::campoEquipoActionPerformed);

        Guardar.setText("Guardar información equipo");
        Guardar.addActionListener(this::GuardarActionPerformed);

        datos.setText("Datos de cada participante  ");

        nombreParticipante.setText("Nombre");

        apellidoParticipante.setText("Apellido");

        campoNombreParticipante.addActionListener(this::campoNombreParticipanteActionPerformed);

        campoApellidoParticipante.addActionListener(this::campoApellidoParticipanteActionPerformed);

        datosParticipante.setText("Añadir participante");
        datosParticipante.addActionListener(this::datosParticipanteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Guardar)
                            .addComponent(nombreequipo)
                            .addComponent(Universidad)
                            .addComponent(lenguaje)
                            .addComponent(numeroIntegrantes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoEquipo)
                                .addComponent(campoUniversidad)
                                .addComponent(campoLenguaje)
                                .addComponent(campoNumeroIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datos)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombreParticipante)
                                    .addComponent(apellidoParticipante))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoNombreParticipante, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(campoApellidoParticipante))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(datosParticipante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreequipo)
                    .addComponent(campoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Universidad)
                    .addComponent(campoUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lenguaje)
                    .addComponent(campoLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroIntegrantes)
                    .addComponent(campoNumeroIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Limpiar))
                .addGap(39, 39, 39)
                .addComponent(datos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreParticipante)
                    .addComponent(campoNombreParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoParticipante)
                    .addComponent(campoApellidoParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(datosParticipante)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEquipoActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        campoEquipo.setText("");
        campoLenguaje.setText("");
        campoUniversidad.setText("");
        campoNumeroIntegrantes.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        String nom;
        String uni;
        String lgje;
        int numInt;
        
        
        nom = campoEquipo.getText();
        uni = campoUniversidad.getText();
        lgje = campoLenguaje.getText();
        numInt= Integer.parseInt(campoNumeroIntegrantes.getText());
        
        //Nos cercioramos de que sí tenemos el número indicado de integrantes
        int prueba = EquipoMaratónProgramación.validarNumero(numInt);
        
        if (prueba == 0){
            JOptionPane.showMessageDialog(null,"El equipo debe tener 2 ó 3 integrantes","Cantidad requerida",JOptionPane.ERROR_MESSAGE);
        }
        else{
            EquipoMaratónProgramación equipo = new EquipoMaratónProgramación(nom, uni,lgje,numInt);
            JOptionPane.showMessageDialog(null,"Información guardada con éxito","Información guardada", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
        
        
        //Pasamos a la información de cada integrante
        
        
        
        
        
        
    }//GEN-LAST:event_GuardarActionPerformed

    private void campoNombreParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreParticipanteActionPerformed

    private void campoApellidoParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoParticipanteActionPerformed

    private void datosParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosParticipanteActionPerformed
        // TODO add your handling code here:
        String nombreIntegrante;
        String apellidoIntegrante;
        int pruebaNombre;
        int pruebaApellido;
        int contador=0;
        int numInt;
        
       
        nombreIntegrante = campoNombreParticipante.getText();
        apellidoIntegrante = campoApellidoParticipante.getText();
        numInt= Integer.parseInt(campoNumeroIntegrantes.getText());
        
        
        //Verificamos que esten en formato conrrecto los datos
        pruebaNombre = EquipoMaratónProgramación.validarCampo(nombreIntegrante);
        pruebaApellido = EquipoMaratónProgramación.validarCampo(apellidoIntegrante);
        
        if (pruebaNombre ==1){
            JOptionPane.showMessageDialog(null,"El nombre no puede tener dígitos","Nombre con dígitos",JOptionPane.ERROR_MESSAGE);
        }
        else if (pruebaNombre == 2){
            JOptionPane.showMessageDialog(null,"La longitud del nombre no debe ser superior a 20 caracteres.","Límite de caracteres",JOptionPane.ERROR_MESSAGE);
        }
        if (pruebaApellido ==1){
            JOptionPane.showMessageDialog(null,"El apellido no puede tener dígitos","Apellido con dígitos",JOptionPane.ERROR_MESSAGE);
        }
        else if (pruebaApellido ==2){
            JOptionPane.showMessageDialog(null,"La longitud del apellido no debe ser superior a 20 caracteres.","Límite de caracteres",JOptionPane.ERROR_MESSAGE);
        }
        if (pruebaNombre==0 && pruebaApellido ==0){

            Programador integrante = new Programador(nombreIntegrante, apellidoIntegrante);
            EquipoMaratónProgramación.añadir(integrante);
        }
        
        campoNombreParticipante.setText("");
        campoApellidoParticipante.setText("");

    }//GEN-LAST:event_datosParticipanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaEquipo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Universidad;
    private javax.swing.JLabel apellidoParticipante;
    private javax.swing.JTextField campoApellidoParticipante;
    private javax.swing.JTextField campoEquipo;
    private javax.swing.JTextField campoLenguaje;
    private javax.swing.JTextField campoNombreParticipante;
    private javax.swing.JTextField campoNumeroIntegrantes;
    private javax.swing.JTextField campoUniversidad;
    private javax.swing.JLabel datos;
    private javax.swing.JButton datosParticipante;
    private javax.swing.JLabel lenguaje;
    private javax.swing.JLabel nombreParticipante;
    private javax.swing.JLabel nombreequipo;
    private javax.swing.JLabel numeroIntegrantes;
    // End of variables declaration//GEN-END:variables
}
